version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Nicosia
    open-pull-requests-limit: 10

  - package-ecosystem: gradle
    directory: /apps/jetbrains
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Nicosia
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Nicosia
    open-pull-requests-limit: 10
